Fix dead link to transaction docs
Pylons/pyramid_tm pull request #79
Opened 2021-05-03 17:23 UTC by lkuchenb

The ZODB link in the docs is dead. I assume the original target page is still available under

https://zodb.org/en/latest/articles/old-guide/transactions.html

however the URL indicates it may not be for much longer. I guess linking to the transaction docs instead would make sense.

2021-05-03 19:40 UTC, stevepiercy requested changes

2021-05-03 19:40 UTC, stevepiercy commented on docs/index.rst
> +<https://transaction.readthedocs.io>`_ for an
Let's save a redirect.

```suggestion
<https://transaction.readthedocs.io/en/latest/>`_ for an
```

2021-05-03 22:03 UTC, lkuchenb commented on docs/index.rst
> +<https://transaction.readthedocs.io>`_ for an
Sure. Fixed.

2021-05-04 00:38 UTC, stevepiercy commented on docs/index.rst
> +<https://transaction.readthedocs.io>`_ for an
Thank you!

2021-05-04 00:38 UTC, stevepiercy approved these changes

2021-05-04 00:47 UTC, merged